version: '3.9'

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: maureva
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: maureva
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /maureva-flight-app/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    image: jboss/keycloak:13.0.0
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

  app:
    depends_on:
      - postgres
    build: ./maureva-flight-app
    container_name: maureva-flight-app
    ports:
      - "8000:8000"
    restart: always
    networks:
      - local-keycloak

networks:
  local-keycloak:
