package com.maureva.domain.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Country {
    AFGHANISTAN("Afghanistan"),
    ALBANIE("Albanie"),
    ALGÉRIE("Algérie"),
    ANDORRE("Andorre"),
    ANGOLA("Angola"),
    ANGLETERRE("Angleterre"),
    ANTIGUA_ET_BARBUDA("Antigua et Barbuda"),
    ARGENTINE("Argentine"),
    ARMÉNIE("Arménie"),
    AUSTRALIE("Australie"),
    AUTRICHE("Autriche"),
    AZERBAÏDJAN("Azerbaïdjan"),
    BAHAMAS("Bahamas"),
    BAHREÏN("Bahreïn"),
    BANGLADESH("Bangladesh"),
    BARBADE("Barbade"),
    BÉLARUS("Bélarus"),
    BELGIQUE("Belgique"),
    BÉLIZE("Bélize"),
    BÉNIN("Bénin"),
    BHOUTAN("Bhoutan"),
    BOLIVIE("Bolivie"),
    BOSNIE_HERZÉGOVINE("Bosnie-Herzégovine"),
    BOTSWANA("Botswana"),
    BRÉSIL("Brésil"),
    BRUNÉI("Brunéi"),
    BULGARIE("Bulgarie"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CABO_VERDE("Cap-Vert"),
    CAMBODGE("Cambodge"),
    CAMEROUN("Cameroun"),
    CANADA("Canada"),
    RÉPUBLIQUE_CENTRAFRICAINE("République centrafricaine"),
    TCHAD("Tchad"),
    CHILI("Chili"),
    CHINE("Chine"),
    COLOMBIE("Colombie"),
    COMORES("Comores"),
    RÉPUBLIQUE_DÉMOCRATIQUE_DU_CONGO("République démocratique du Congo"),
    COSTA_RICA("Costa Rica"),
    CROATIE("Croatie"),
    CUBA("Cuba"),
    CHYPRE("Chypre"),
    RÉPUBLIQUE_TCHÈQUE("République tchèque"),
    DANEMARK("Danemark"),
    DJIBOUTI("Djibouti"),
    DOMINIQUE("Dominique"),
    RÉPUBLIQUE_DOMINICAINE("République dominicaine"),
    TIMOR_ORIENTAL("Timor oriental"),
    ÉQUATEUR("Équateur"),
    ÉGYPTE("Égypte"),
    EL_SALVADOR("Salvador"),
    GUINÉE_ÉQUATORIALE("Guinée équatoriale"),
    ÉRYTHRÉE("Érythrée"),
    ESTONIE("Estonie"),
    ESWATINI("Eswatini"),
    ÉTHIOPIE("Éthiopie"),
    FIJI("Fidji"),
    FINLANDE("Finlande"),
    FRANCE("France"),
    GABON("Gabon"),
    GAMBIE("Gambie"),
    GÉORGIE("Géorgie"),
    ALLEMAGNE("Allemagne"),
    GHANA("Ghana"),
    GRÈCE("Grèce"),
    GRENADE("Grenade"),
    GUATEMALA("Guatemala"),
    GUINÉE("Guinée"),
    GUINÉE_BISSAU("Guinée-Bissau"),
    GUYANA("Guyana"),
    HAÏTI("Haïti"),
    HONDURAS("Honduras"),
    HONGRIE("Hongrie"),
    ISLANDE("Islande"),
    INDE("Inde"),
    INDONÉSIE("Indonésie"),
    IRAN("Iran"),
    IRAQ("Irak"),
    IRLANDE("Irlande"),
    ISRAËL("Israël"),
    ITALIE("Italie"),
    CÔTE_D_IVOIRE("Côte d'Ivoire"),
    JAMAÏQUE("Jamaïque"),
    JAPON("Japon"),
    JORDANIE("Jordanie"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRIBATI("Kiribati"),
    KOWEÏT("Koweït"),
    KIRGHIZISTAN("Kirghizistan"),
    LAOS("Laos"),
    LETTONIE("Lettonie"),
    LIBAN("Liban"),
    LESOTHO("Lesotho"),
    LIBÉRIA("Libéria"),
    LIBYE("Libye"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIE("Lituanie"),
    LUXEMBOURG("Luxembourg"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAISIE("Malaisie"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTE("Malte"),
    ÎLES_MARSHALL("Îles Marshall"),
    MAURITANIE("Mauritanie"),
    MAURICE("Maurice"),
    MEXIQUE("Mexique"),
    MICRONÉSIE("Micronésie"),
    MOLDAVIE("Moldavie"),
    MONACO("Monaco"),
    MONGOLIE("Mongolie"),
    MONTÉNÉGRO("Monténégro"),
    MAROC("Maroc"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIE("Namibie"),
    NAURU("Nauru"),
    NÉPAL("Népal"),
    PAYS_BAS("Pays-Bas"),
    NOUVELLE_ZÉLANDE("Nouvelle-Zélande"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGÉRIA("Nigéria"),
    CORÉE_DU_NORD("Corée du Nord"),
    MACÉDOINE_DU_NORD("Macédoine du Nord"),
    NORVÈGE("Norvège"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PALAOS("Palaos"),
    PANAMA("Panama"),
    PAPOUASIE_NOUVELLE_GUINÉE("Papouasie-Nouvelle-Guinée"),
    PARAGUAY("Paraguay"),
    PÉROU("Pérou"),
    PHILIPPINES("Philippines"),
    POLOGNE("Pologne"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    ROUMANIE("Roumanie"),
    RUSSIE("Russie"),
    RWANDA("Rwanda"),
    SAINT_KITTS_ET_NEVIS("Saint-Kitts-et-Nevis"),
    SAINTE_LUCIE("Sainte-Lucie"),
    SAINT_VINCENT_ET_LES_GRENADINES("Saint-Vincent-et-les-Grenadines"),
    SAMOA("Samoa"),
    SAINT_MARIN("Saint-Marin"),
    SAO_TOMÉ_ET_PRINCIPE("Sao Tomé-et-Principe"),
    ARABIE_SAOUDITE("Arabie saoudite"),
    SÉNÉGAL("Sénégal"),
    SERBIE("Serbie"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPORE("Singapore"), // TODO : It is what it is
    SINGAPOUR("Singapour"),
    SLOVAQUIE("Slovaquie"),
    SLOVÉNIE("Slovénie"),
    ÎLES_SOLOMON("Îles Salomon"),
    SOMALIE("Somalie"),
    AFRIQUE_DU_SUD("Afrique du Sud"),
    CORÉE_DU_SUD("Corée du Sud"),
    SOUDAN_DU_SUD("Soudan du Sud"),
    ESPAGNE("Espagne"),
    SRI_LANKA("Sri Lanka"),
    SOUDAN("Soudan"),
    SURINAME("Suriname"),
    SUÈDE("Suède"),
    SUISSE("Suisse"),
    SYRIE("Syrie"),
    TAÏWAN("Taïwan"),
    TADJIKISTAN("Tadjikistan"),
    TANZANIE("Tanzanie"),
    THAÏLANDE("Thaïlande"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINITÉ_ET_TOBAGO("Trinité-et-Tobago"),
    TUNISIE("Tunisie"),
    TURQUIE("Turquie"),
    TURKMÉNISTAN("Turkménistan"),
    TUVALU("Tuvalu"),
    OUGANDA("Ouganda"),
    UKRAINE("Ukraine"),
    ÉMIRATS_ARABES_UNIS("Émirats arabes unis"),
    ROYAUME_UNI("Royaume-Uni"),
    ÉTATS_UNIS("États-Unis"),
    URUGUAY("Uruguay");

    private final String name;

    @Override
    public String toString() {
        return name;
    }

}
